### ISSUE TITLE
Implement post notification to user (maybe with standard sound alerts)

### ISSUE THREAD

**Issue by devahmedshendy** [0xLeif/RobotKit#4]
I thought this would be a good feature to add, I like to contribute with this feature.

So, after a several tasks Robot should post a notification to the user and maybe with some standard sounds if task(s) done successfully or not. Like we get from Xcode for successful and failed builds.

What do you think @0xLeif ?

I never did such feature, this is why I opened this issue to see your opinion and guide myself with any hints/discussions on where to start.

**Comment by 0xLeif** [comment]
@devahmedshendy This is a great suggestion! 

I initially think this would just be another variable in [Robot.swift](https://github.com/0xLeif/RobotKit/blob/main/Sources/RobotKit/Robot.swift#L22-L34)

Something like...
```swift
/// Robot control of the notifications
public let notification = RobotNotification()
```

Then I would just expect this ticket to implement `RobotNotification`. We could start with just one function, `push` where we supply some information for the notification.

My only concern is push notifications require permissions..  I also have this general Swift push notifications code working too https://github.com/0xOpenBytes/o/tree/main/Sources/o/Notifications

Let me know if you have any questions!
